hostname="auryn"
keymap="de.kbd"
wlans_iwlwifi0="wlan0"
ifconfig_wlan0="WPA  DHCP"
ifconfig_wlan0_ipv6="inet6 accept_rtadv"
create_args_wlan0="country DE regdomain ETSI"
sshd_enable="YES"
ntpd_enable="YES"
ntpd_sync_on_start="YES"

# disable moused for now, there is native support in X and Wayland
moused_nondefault_enable="NO"

# Set dumpdev to "AUTO" to enable crash dumps, "NO" to disable
dumpdev="NO"

# enable ZFS fs
zfs_enable="YES"


# enable drm-next-kmd for video
kld_list="if_iwlwifi i915_kbl_dmc_ver1_04_bin i915kms nvidia-drm fusefs nvidia-modeset"
seatd_enable="YES"

autofs_enable="YES"
devfs_system_ruleset="localrules"
lightdm_enable="NO"

performace_cx_lowest="Cmax"
economy_cx_lowest="Cmax"

# Zeroconf DNS enable
avahi_daemon_enable="YES"
avahi_dnsconfig_enable="YES"

# don't let syslog open network sockets
syslogd_flags="-ss"

# disable sendmail daemon
sendmail_enable="NONE"

# sync clock on boot
ntpd_enable="YES" 
ntpd_flags="-g"

# enable dbus
dbus_enable="YES"

# enable bluetooth
hcsecd_enable="YES"
sdpd_enable="YES"

# enable printing
cupsd_enable="YES"

# enable webcam (works fine in chrome)
webcamd_enable="YES"

# enable wireguard for vpn
wireguard_enable="YES"
wireguard_interfaces="wg0"
